### PR TITLE
Fix Page 7 Info

### PR DESCRIPTION
**Pull request by ExtremeFiretop**
Fix Page 7 Information

### CODE REVIEW

**Comment by ViktorJp** [comment]
@ExtremeFiretop -- I really appreciate your hard work on this!!  So when I tested this out on my end, it seems to prefer whatever is in my dnsmasq than what custom names were given in the client names NVRAM entry... as shown below...

image

And I still think this might be because it's prematurely break-ing with that new break that was added, instead of allowing it to loop through the client names NVRAM entry until it matches a MAC address... which then gives me this (when that break is removed and looping is back on -- but caused an endless loop for you)

image

For some reason... the LAN section isn't resolving my preferred names any longer, and need to look into further.

**Comment by ExtremeFiretop** [comment]
Hey @ViktorJp 

I've fixed the first issue of the endless loop for me and not being able to reach the right device for you
(I only had the one device in the nvram so naturally it would always either pass on the first try or fail completely)

The LAN is populating for me now, that was a different issue.

Now the only outstanding is:

1. Missing names on VLAN
2. Missing IP and Name on Guest WiFi?

Those two might need some relogic since in my case, they are both trying to display the same info essentially.

**Comment by ExtremeFiretop** [comment]
I think I fixed the VLANs as well :) Works for me!

**Comment by ExtremeFiretop** [comment]
That's it.

I'm done and this is ready for merge when you are @ViktorJp :)

**Pull request merged**
